version: 2
references:
  im36: &im36
    docker:
      - image: circleci/python:3.6.1
    
  wd: &wd
    working_directory: ~/repo

  runall_tests: &runall_tests
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover tests

      - store_artifacts:
          path: test-reports
          destination: test-reports

jobs:
  py36:
    <<: *im36 
    <<: *wd
    <<: *runall_tests

workflows:
    version: 2
    all:
      jobs:
        - py36 
