version: 2
jobs:
  py36:
    docker:
      # Minimal image required
      - image: circleci/python:3.6.1
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover tests

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
    version: 2
    all:
      jobs:
        - py36 
