version: 2

references:
  im36: &im36
    docker:
      - image: themattrix/tox   

  wd: &wd
    working_directory: ~/repo

  runall: &runall
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: run tests
          command: |
            # Faster to just test one env first
            pip3.6 install --user flake8
            pip3.6 install --user numpy
            pip3.6 install --user scipy
            python3.6 -m flake8 --show-source .
            python3.6 -m unittest discover tests -v

            # Test python-dependency matrix with tox
            pip3.6 install --user tox
            tox

            # Run with coverage
            pip3.6 install --user coverage
            export PATH=~/.local/bin:${PATH}
            coverage run -m unittest discover tests
            apt-get -yq update
            apt-get -yq install curl
            bash <(curl -s https://codecov.io/bash)

      - save_cache:
          paths:
            - ~/.local
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  run_tests_only: &run_tests_only
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: run tests
          command: |
            # Faster to just test one env first
            pip3.6 install --user flake8
            pip3.6 install --user numpy
            pip3.6 install --user scipy
            python3.6 -m flake8 --show-source .
            python3.6 -m unittest discover tests -v

      - save_cache:
          paths:
            - ~/.local
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  pypi_wheels: &pypi_wheels
    steps:
      - checkout

      - run:
          name: Deploy dist and wheels
          command: |
            pip3.6 install --user flake8
            pip3.6 install --user numpy
            pip3.6 install --user scipy
            python3.6 -m flake8 --show-source .
            python3.6 -m unittest discover tests -v
            python3.6 --version
            pip3.6 --version
            pip3.6 install --user -U twine wheel setuptools
            export PATH=~/.local/bin:${PATH}
            twine --version
            wheel version
            python3.6 setup.py sdist
            python3.6 setup.py bdist_wheel
            twine upload --username vramasub --password ${PYPI_PASSWORD} dist/*

jobs:
  complete:
    <<: *im36
    <<: *wd
    <<: *runall
  test_only:
    <<: *im36
    <<: *wd
    <<: *run_tests_only
  build_and_deploy:
    <<: *im36
    <<: *wd
    <<: *pypi_wheels

workflows:
  version: 2
  testing:
    jobs:
      - complete:
          filters:
            branches:
              only:
                - master
                - develop
                - /release-*/
      - test_only:
          filters:
            branches:
              ignore:
                - master
                - develop
                - /release-*/
  deploy:
    jobs:
      - build_and_deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
